from __future__ import annotations

import asyncio
import hashlib
import json
from collections.abc import Callable
from pathlib import Path
from typing import Protocol, TypeVar

from openai import AsyncOpenAI
from pydantic import BaseModel, ValidationError

ModelT = TypeVar("ModelT", bound=BaseModel)


class V32AgentProvider(Protocol):
    run_mode: str

    def model_name_for(self, kind: str) -> str: ...

    async def resolve(
        self,
        *,
        kind: str,
        instruction: str,
        payload: object,
        response_type: type[ModelT],
        fallback: Callable[[], ModelT],
    ) -> ModelT: ...


def _fallback_value(fallback: Callable[[], ModelT], *, used: bool) -> ModelT:
    value = fallback()
    if used and "fallback_used" in type(value).model_fields:
        return value.model_copy(update={"fallback_used": True})
    return value


def _same_identity(value: BaseModel, expected: BaseModel) -> bool:
    identity_fields = ("branch_id", "province_code", "automaker_id", "round")
    return all(
        getattr(value, field) == getattr(expected, field)
        for field in identity_fields
        if field in type(expected).model_fields
    )


class V32FakeAgentProvider:
    run_mode = "fake"

    def model_name_for(self, kind: str) -> str:
        del kind
        return "deterministic-fallback"

    async def resolve(
        self,
        *,
        kind: str,
        instruction: str,
        payload: object,
        response_type: type[ModelT],
        fallback: Callable[[], ModelT],
    ) -> ModelT:
        del kind, instruction, payload, response_type
        # Local deterministic mode is a visible outage fallback, never a simulated
        # model success and never a source for a Luna-labelled cache entry.
        return _fallback_value(fallback, used=True)


class V32CachedAgentProvider:
    run_mode = "cache"

    def __init__(self, cache_dir: Path) -> None:
        self.cache_dir = cache_dir

    def model_name_for(self, kind: str) -> str:
        del kind
        return "cached-agent-output"

    @staticmethod
    def _key(kind: str, payload: object, response_type: type[BaseModel]) -> str:
        raw = json.dumps(
            {"kind": kind, "payload": payload, "schema": response_type.model_json_schema()},
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            default=str,
        )
        return hashlib.sha256(raw.encode()).hexdigest()

    async def resolve(
        self,
        *,
        kind: str,
        instruction: str,
        payload: object,
        response_type: type[ModelT],
        fallback: Callable[[], ModelT],
    ) -> ModelT:
        del instruction
        key = self._key(kind, payload, response_type)
        path = self.cache_dir / f"{kind}_{key}.json"
        if path.exists():
            expected = fallback()
            cached = response_type.model_validate_json(path.read_text(encoding="utf-8"))
            return (
                cached if _same_identity(cached, expected) else _fallback_value(fallback, used=True)
            )
        # A cache miss is an explicit fallback. Never persist deterministic output as if it
        # had been generated by a model.
        return _fallback_value(fallback, used=True)


class V32LiveAgentProvider:
    run_mode = "live"

    def __init__(
        self,
        *,
        client: AsyncOpenAI,
        province_model: str,
        automaker_model: str,
        max_tokens: int,
        semaphore: asyncio.Semaphore | None = None,
    ) -> None:
        self.client = client
        self.province_model = province_model
        self.automaker_model = automaker_model
        self.max_tokens = max_tokens
        self.semaphore = semaphore or asyncio.Semaphore(16)

    def model_name_for(self, kind: str) -> str:
        return self.automaker_model if kind.startswith("automaker") else self.province_model

    async def resolve(
        self,
        *,
        kind: str,
        instruction: str,
        payload: object,
        response_type: type[ModelT],
        fallback: Callable[[], ModelT],
    ) -> ModelT:
        model = self.automaker_model if kind.startswith("automaker") else self.province_model
        messages: list[dict[str, str]] = [
            {
                "role": "system",
                "content": (
                    "你是 PolicyScope V3.2 的结构化策略 Agent。只返回符合 Schema 的 JSON；"
                    "不得输出最终指标、现实预测、承诺或思维链。所有解释必须公开、简短、可审计。"
                ),
            },
            {
                "role": "user",
                "content": json.dumps(
                    {
                        "instruction": instruction,
                        "input": payload,
                        "schema": response_type.model_json_schema(),
                    },
                    ensure_ascii=False,
                    default=str,
                ),
            },
        ]
        for attempt in range(2):
            try:
                async with self.semaphore:
                    response = await self.client.chat.completions.create(
                        model=model,
                        messages=messages,
                        response_format={
                            "type": "json_schema",
                            "json_schema": {
                                "name": response_type.__name__.lower(),
                                "strict": True,
                                "schema": response_type.model_json_schema(),
                            },
                        },
                        max_completion_tokens=self.max_tokens,
                    )
                value = response_type.model_validate_json(
                    response.choices[0].message.content or "{}"
                )
                expected = fallback()
                if not _same_identity(value, expected):
                    return _fallback_value(fallback, used=True)
                return value
            except (ValidationError, ValueError, json.JSONDecodeError) as exc:
                messages.append(
                    {
                        "role": "user",
                        "content": json.dumps(
                            {"repair": "修复上一响应，仅返回完整 JSON。", "error": str(exc)[:800]},
                            ensure_ascii=False,
                        ),
                    }
                )
            except Exception:
                break
            if attempt == 1:
                break
        return _fallback_value(fallback, used=True)


def build_v32_agent_provider(legacy_provider: object, cache_dir: Path) -> V32AgentProvider:
    run_mode = getattr(legacy_provider, "run_mode", "fake")
    if run_mode == "live" and all(
        hasattr(legacy_provider, field)
        for field in ("client", "province_model", "automaker_model", "max_tokens")
    ):
        return V32LiveAgentProvider(
            client=legacy_provider.client,
            province_model=legacy_provider.province_model,
            automaker_model=legacy_provider.automaker_model,
            max_tokens=legacy_provider.max_tokens,
            semaphore=getattr(legacy_provider, "semaphore", None),
        )
    if run_mode == "cache":
        return V32CachedAgentProvider(cache_dir / "decisions")
    return V32FakeAgentProvider()
