export const SIMULATION_EVENT_TYPES = [
  "experiment.started",
  "province.persona.ready",
  "central.directive.completed",
  "central.directive.approved",
  "phase.started",
  "province.decision.started",
  "province.decision.completed",
  "province.decision.fallback",
  "enterprise.batch.started",
  "enterprise.batch.completed",
  "enterprise.batch.fallback",
  "enterprise.aggregate.updated",
  "province.feedback.completed",
  "province.adjustment_intent.completed",
  "province.strategy.changed",
  "environment.updated",
  "world_state.updated",
  "central.intervention.proposed",
  "central.intervention.approved",
  "central.intervention.rejected",
  "checkpoint.created",
  "branch.created",
  "phase.completed",
  "experiment.completed",
] as const;

export const EVENT_LABELS: Record<string, string> = {
  "experiment.started": "推演已创建",
  "province.persona.ready": "省级决策画像已冻结",
  "central.directive.completed": "中央草案已生成",
  "central.directive.approved": "中央指令已审批",
  "phase.started": "阶段开始",
  "phase.completed": "阶段完成",
  "province.decision.started": "省级智能体开始决策",
  "province.decision.completed": "省级策略已生成",
  "province.decision.fallback": "省级策略已降级",
  "enterprise.batch.started": "企业批量决策开始",
  "enterprise.batch.completed": "六类企业响应完成",
  "enterprise.batch.fallback": "整省企业响应已降级",
  "enterprise.aggregate.updated": "企业群体指标已聚合",
  "province.feedback.completed": "地方反馈已形成",
  "province.adjustment_intent.completed": "地方调整意向已形成",
  "province.strategy.changed": "省级策略迁移已记录",
  "environment.updated": "环境完成结算",
  "world_state.updated": "权威状态已提交",
  "central.intervention.proposed": "中央研判建议已生成",
  "central.intervention.approved": "干预已获用户批准",
  "central.intervention.rejected": "用户保留原始方案",
  "checkpoint.created": "T3 检查点已冻结",
  "branch.created": "干预方案分支已创建",
  "experiment.completed": "双方案对照与复盘已完成",
};
