const productLabels = {
  policy_comparison: "政策对比",
  policy_stress_test: "政策压力测试",
  event_counterfactual: "事件反事实",
  province_initial: "省级初始行动",
  automaker_initial: "车企初步响应",
  province_revision: "省级策略调整",
  automaker_negotiation: "合作协商",
  province_counter_response: "方案确认",
  automaker_final: "车企最终行动",
  environment_settlement: "环境结算",
  maintain: "维持",
  follow: "跟进",
  differentiate: "差异化",
  coordinate: "协作",
  matched: "双向已匹配",
  unmatched: "单向未匹配",
  low: "低",
  medium: "中",
  high: "高",
  verified: "可信数据",
  proxy: "代理数据",
  rejected: "已拒绝",
  accept: "接受",
  reject: "拒绝",
  offer: "合作方案",
  no_offer: "未发起合作",
  consumer: "消费端支持",
  fixed_cost: "固定成本支持",
  variable_cost: "可变成本支持",
  balanced: "均衡支持",
  resource_invalid: "资源约束未通过",
  scenario_assumption: "情景假设",
  control: "原始方案",
  treatment: "干预方案",
  before_province_initial: "推演开始前",
  after_province_initial: "省份初始行动后",
  after_automaker_initial: "企业初步响应后",
  expand: "扩大渠道",
  reduce: "收缩渠道",
  new_plant: "模拟新建产能",
  delay: "模拟延后产能",
  fiscal_rigidity: "财政刚性约束",
  weak_consumer_wtp: "消费意愿代理较弱",
  weak_industry_base: "产业基础代理较弱",
  battery_distance: "电池供应距离约束",
  talent_cost: "人才成本约束",
  energy_cost: "能源成本约束",
  logistics_cost: "物流成本约束",
  mass_market: "大众价格带",
  mainstream: "主流价格带",
  premium: "高端价格带",
  regional_development_gap: "区域发展差距",
  central_fiscal_burden: "中央财政负担",
  local_fiscal_pressure: "地方财政压力",
  nev_demand: "新能源汽车需求",
  new_investment_concentration: "新增投资集中度",
  industrial_agglomeration: "产业集聚度",
  overall_support_intensity: "总体支持强度",
  subsidy_mix: "三类政策份额",
  coordination_target_codes: "合作对象",
  available_policy_budget: "可用政策预算",
  accepted_coordination_count: "已接受合作数",
  province_policy_score: "省级政策吸引力",
  gt: "高于",
  gte: "不低于",
  lt: "低于",
  lte: "不高于",
  eq: "等于",
} as const;

export function productLabel(value: string): string {
  if (value in productLabels) return productLabels[value as keyof typeof productLabels];
  if (import.meta.env.DEV) console.warn(`[PolicyScope] missing product label: ${value}`);
  return "未知状态";
}
