export type Phase = "SETUP" | "Y1_Q1" | "Y1_Q2" | "Y1_Q3" | "Y1_Q4" | "YEAR1_REVIEW" | "Y2_Q1" | "Y2_Q2" | "Y2_Q3" | "Y2_Q4" | "COMPLETE";
export type RunMode = "live" | "cache" | "fake" | "fallback";
export type DataQuality = "verified" | "proxy" | "demo";
export type BranchKind = "control" | "treatment";

export interface ProvenanceRecord { source_name: string; source_url: string; source_year: number; original_unit: string; transformation: string; missing_value_handling: string; quality: DataQuality; }
export interface Policy { schema_version: "policy-v3"; policy_id: string; domain: string; reference_policy_year: 2025; input_mode: "absolute" | "delta"; west_central_share: number; central_central_share: number; east_central_share: number; share_adjustments: { west: number; central: number; east: number }; consumer_subsidy_standard_version: string; eligibility_rule_version: string; primary_goal: string; status: string; mechanism_version: string; }
export interface PolicyFieldChange { path: string; from_value: number; to_value: number; }
export interface CentralDirective { schema_version: string; directive_id: string; policy: Policy; policy_objectives: string[]; hard_constraints: string[]; evidence_refs: string[]; public_summary: string; approval_status: "draft" | "awaiting_approval" | "approved" | "rejected"; }
export interface ProvinceProfile { schema_version: "province-profile-v4"; province_code: string; name: string; short_name: string; policy_region: "east" | "central" | "west"; baseline_year: number; fiscal_capacity: number; fiscal_rigidity: number; nev_industry_base: number; vehicle_manufacturing_base: number; components_base: number; rd_activity: number; market_scale: number; willingness_to_pay_index: number; land_cost_index: number; talent_cost_index: number; energy_cost_index: number; logistics_cost_index: number; battery_supply_distance_index: number; charging_infrastructure_index: number; urbanization_index: number; vehicle_consumption_index: number; nev_penetration_index: number; peer_province_codes: string[]; data_quality: DataQuality; provenance: Record<string, ProvenanceRecord>; }
export interface ProvincePersona { schema_version: "province-persona-v2"; province_code: string; axes: Record<string, number>; primary_type: string; secondary_type: string | null; key_constraints: string[]; data_quality: "proxy" | "demo"; summary: string; }
export interface SubsidyMix { consumer: number; fixed_cost: number; variable_cost: number; }
export interface ProvinceAction { schema_version: "province-action-v4"; action_id: string; previous_action_id: string | null; province_code: string; phase: Phase; overall_support_intensity: number; subsidy_mix: SubsidyMix; peer_response_mode: "follow" | "differentiate" | "hold"; observed_peer_codes: string[]; reason_codes: string[]; summary: string; run_mode: RunMode; fallback_used: boolean; fallback_reason: string | null; }
export interface ProvinceFeedback { schema_version: "province-feedback-v4"; feedback_id: string; province_code: string; phase: "Y1_Q4"; strategy_assessment: string; signals: Array<{ signal_type: string; direction: string; severity: string; evidence_refs: string[] }>; constraints: string[]; adjustment_intents: Array<{ path: string; direction: string; reason: string }>; central_share_recommendation: { west_delta: number; central_delta: number; east_delta: number }; reason_codes: string[]; evidence_refs: string[]; summary: string; }
export interface ProvinceState { schema_version: "province-state-v4"; province_code: string; phase: Phase; local_matching_burden_index: number; fiscal_space_index: number; local_support_index: number; demand_index: number; industry_activity_index: number; development_index: number; fiscal_pressure_index: number; last_action_id: string | null; last_feedback_id: string | null; }
export interface ProvinceMarketAction { province_code: string; sales_investment_intensity: number; channel_strategy: "expand" | "maintain" | "reduce"; }
export interface FacilityAction { province_code: string; action: "new_plant" | "expand" | "delay"; investment_intensity: number; }
export interface AutomakerProfile { schema_version: "automaker-profile-v1"; automaker_id: string; display_name: string; entity_scope: string; baseline_year: 2025; sales_scale_index: number; sales_growth_index: number; profitability_index: number; liquidity_index: number; capacity_utilization_index: number; channel_coverage_by_province: Array<{ province_code: string; coverage_index: number }>; production_footprint: Array<{ province_code: string; role: string; baseline_note: string; provenance_ref: string }>; product_segment_mix: Record<string, number>; technology_route_mix: Record<string, number>; expansion_posture: string; data_quality: DataQuality; provenance: Record<string, ProvenanceRecord>; }
export interface AutomakerAction { schema_version: "automaker-action-v1"; action_id: string; previous_action_id: string | null; automaker_id: string; phase: Phase; province_market_actions: ProvinceMarketAction[]; facility_actions: FacilityAction[]; simulated_roi_band: string; reason_codes: string[]; summary: string; run_mode: RunMode; fallback_used: boolean; fallback_reason: string | null; }
export interface AutomakerState { schema_version: "automaker-state-v1"; automaker_id: string; phase: Phase; simulated_roi_index: number; sales_activity_index: number; facility_activity_index: number; operating_cost_index: number; last_action_id: string | null; }
export interface AutomakerMeta { automaker_id: string; display_name: string; schema_version: string; baseline_year: number; data_quality: DataQuality; representative_set_disclaimer: string; }
export interface NationalMetrics { schema_version: string; regional_development_gap: number; central_fiscal_burden: number; local_fiscal_pressure: number; nev_demand: number; new_investment_concentration: number; industrial_agglomeration: number; }
export type NationalMetricKey = Exclude<keyof NationalMetrics, "schema_version">;
export interface InterventionProposal { schema_version: string; proposal_id: string; proposed_policy: Policy; parameter_changes: PolicyFieldChange[]; expected_directions: Record<string, string>; tradeoffs: string[]; evidence_refs: string[]; public_summary: string; approval_status: string; }
export interface CentralIntervention { schema_version: string; intervention_id: string; approved_policy: Policy; approved_changes: PolicyFieldChange[]; approved_at: string; approved_by: "user"; approval_status: "approved"; }
export interface CentralReview { schema_version: string; review_id: string; review_mode: "comparison" | "single_branch"; findings: Array<{ title: string; summary: string; evidence_refs: string[]; tradeoff: string | null }>; limitations: string[]; public_summary: string; }
export interface MechanismContribution { schema_version: string; formula_version: string; province_code: string | null; target_metric: string; terms: Array<{ name: string; input_value: number; coefficient: number; contribution: number }>; raw_value: number; clamp_adjustment: number; final_value: number; evidence_refs: string[]; }
export interface WorldState { schema_version: "world-state-v4"; experiment_id: string; branch_id: string; branch_kind: BranchKind; parent_checkpoint_id: string | null; phase: Phase; status: string; run_mode: RunMode; policy: Policy; directive: CentralDirective; national_metrics: NationalMetrics; province_profiles: Record<string, ProvinceProfile>; province_personas: Record<string, ProvincePersona>; province_states: Record<string, ProvinceState>; province_actions: Record<string, ProvinceAction>; province_action_lineage: Record<string, ProvinceAction[]>; province_feedback: Record<string, ProvinceFeedback>; automaker_profiles: Record<string, AutomakerProfile>; automaker_states: Record<string, AutomakerState>; automaker_actions: Record<string, AutomakerAction>; automaker_action_lineage: Record<string, AutomakerAction[]>; contributions: Record<string, MechanismContribution>; fixed_variable_thresholds: Record<string, unknown>; fallback_provinces: string[]; fallback_automakers: string[]; intervention_proposals: InterventionProposal[]; intervention_decision: string | null; approved_intervention: CentralIntervention | null; central_review: CentralReview | null; versions: { data: string; mechanism: string; prompt: string; model: string; app: string }; seed: number; }
export interface Branch { schema_version: string; branch_id: string; experiment_id: string; kind: BranchKind; parent_checkpoint_id: string; current_phase: Phase; }
export interface MetricDelta { control: number; treatment: number; delta: number; }
export interface ProvinceDelta { province_code: string; province_name: string; development_delta: number; demand_delta: number; industry_activity_delta: number; fiscal_pressure_delta: number; }
export interface ComparisonResult { schema_version: "comparison-v4"; experiment_id: string; checkpoint_id: string; control_branch_id: string; treatment_branch_id: string; policy_diff: PolicyFieldChange[]; delta_gap: number; national_metrics: Record<NationalMetricKey, MetricDelta>; province_strategy_transitions: Array<{ province_code: string; province_name: string; changed: boolean; changes: Array<{ path: string; from_value: unknown; to_value: unknown }> }>; automaker_strategy_transitions: Array<{ automaker_id: string; display_name: string; changed_province_allocations: number; facility_changes: unknown[] }>; province_deltas: ProvinceDelta[]; mechanism_totals: Record<string, number>; top_improved: string[]; top_pressured: string[]; central_review: CentralReview | null; }
export interface ProvinceAgentBranchSnapshot { branch_id: string; branch_kind: BranchKind; phase: Phase; state: ProvinceState; current_action: ProvinceAction | null; action_lineage: ProvinceAction[]; feedback: ProvinceFeedback | null; automakers: Array<{ profile: AutomakerProfile; state: AutomakerState | null; action: AutomakerAction | null }>; mechanism_summary: Record<string, number>; evidence_refs: string[]; }
export interface ProvinceAgentDetail { schema_version: string; experiment_id: string; province_code: string; profile: ProvinceProfile; persona: ProvincePersona; top_k_neighbors: Array<{ province_code: string; province_name: string; weight: number }>; branches: Partial<Record<BranchKind, ProvinceAgentBranchSnapshot>>; }
export interface AutomakerDetail { schema_version: string; experiment_id: string; automaker_id: string; profile: AutomakerProfile; branches: Partial<Record<BranchKind, AutomakerState>>; actions: Partial<Record<BranchKind, AutomakerAction | null>>; disclaimer: string; }
export interface SimulationEvent { schema_version: "event-v4"; event_id: string; type: string; experiment_id: string; branch_id: string; phase: Phase; timestamp: string; payload: Record<string, unknown>; }
export type AuditRecordType = "agent_invocation" | "mechanism_explanation" | "decision_gate";
export interface AuditRecord { record_id: string; sequence: number; experiment_id: string; branch_id: string; phase: Phase; timestamp: string; record_hash: string; payload: Record<string, unknown>; }
export interface AuditListResponse { records: AuditRecord[]; next_sequence: number | null; }
export type EvidenceRecord = Record<string, unknown>;
