import type { AutomakerProfile, NationalMetrics, ProvinceProfile, ProvinceState, SubsidyMix } from "./types";

export type V32DataQuality = "verified" | "proxy" | "scenario_assumption";
export type ExperimentType = "policy_comparison" | "policy_stress_test" | "event_counterfactual";
export type JourneyStep = "policy_input" | "central_interpretation" | "experiment_design" | "baseline_confirmation" | "simulation_run" | "result_review";
export type SimulationRound = "province_initial" | "automaker_initial" | "province_revision" | "automaker_negotiation" | "province_counter_response" | "automaker_final" | "environment_settlement";
export type EventTriggerPoint = "before_province_initial" | "after_province_initial" | "after_automaker_initial";

export interface PolicyV4 { schema_version: "policy-v4"; policy_id: string; reference_policy_year: 2025; west_central_share: number; central_central_share: number; east_central_share: number; data_quality: "scenario_assumption"; }
export interface PolicyInterpretation { schema_version: "policy-interpretation-v1"; interpretation_id: string; source_text: string; policy_goals: string[]; target_subjects: string[]; policy_tools: string[]; executable_policy: PolicyV4; execution_period: string; core_constraints: string[]; ambiguities: string[]; unmodeled_clauses: string[]; event_design_hints: string[]; recommended_metrics: string[]; public_summary: string; status: "awaiting_confirmation" | "confirmed"; }
export interface EventPlan { schema_version: "event-plan-v1"; event_plan_id: string; template_id: string; name: string; description: string; trigger_point: EventTriggerPoint; advance_notice: boolean; informed_agent_types: Array<"province" | "automaker">; affected_subjects: Array<"province" | "automaker" | "consumer" | "supply_chain">; mechanism_channels: string[]; branch_scope: "both" | "treatment_only"; intensity: "low" | "medium" | "high"; data_quality: "scenario_assumption"; evidence_refs: string[]; }
export interface ExperimentDesign { schema_version: "experiment-design-v1"; experiment_type: ExperimentType; control_policy: PolicyV4; treatment_policy: PolicyV4; event_plan: EventPlan | null; status: "confirmed"; }
export interface BaselineSnapshot { schema_version: "baseline-snapshot-v2"; checkpoint_schema_version: "checkpoint-v6"; checkpoint_id: string; state_hash: string; province_count: 31; automaker_count: 10; baseline_year: 2025; quality_counts: Array<{ quality: V32DataQuality; field_count: number; explanation: string }>; missing_value_policy: string; uncovered_content: string[]; data_version: string; relation_network_version: string; created_at: string; }
export interface ProvinceActionV5 { schema_version: "province-action-v7"; action_id: string; previous_action_id: string | null; branch_id: string; province_code: string; round: "province_initial" | "province_revision"; overall_support_intensity: number; subsidy_mix: SubsidyMix; response_mode: "maintain" | "follow" | "differentiate" | "coordinate"; observed_peer_codes: string[]; competition_peer_codes: string[]; coordination_target_codes: string[]; primary_policy_focus: "consumer" | "fixed_cost" | "variable_cost" | "balanced"; reason_codes: string[]; summary: string; fallback_used: boolean; }
export interface ProvinceMarketActionV2 { province_code: string; sales_investment_intensity: number; channel_strategy: "expand" | "maintain" | "reduce"; }
export interface AutomakerProvinceSignal { signal_id: string; action_id: string; automaker_id: string; province_code: string; decision: "expand" | "maintain" | "reduce"; investment_direction: "increase" | "maintain" | "decrease"; investment_inclination: number; attraction_factors: string[]; primary_constraints: string[]; reconsideration_condition: string; evidence_refs: string[]; }
export interface ProvinceEnterpriseOfferResponse { response_id: string; branch_id: string; offer_id: string; automaker_id: string; decision: "accept" | "reject" | "counteroffer"; counter_offer_id: string | null; rejection_reason: string | null; opportunity_cost: string; evidence_refs: string[]; }
export interface AutomakerActionV2 { schema_version: "automaker-action-v5"; action_id: string; previous_action_id: string | null; branch_id: string; automaker_id: string; round: "automaker_initial" | "automaker_negotiation" | "automaker_final"; province_market_actions: ProvinceMarketActionV2[]; province_signals: AutomakerProvinceSignal[]; facility_actions: Array<{ province_code: string; action: "new_plant" | "expand" | "delay"; investment_intensity: number }>; enterprise_offer_responses: ProvinceEnterpriseOfferResponse[]; primary_commitment: string; simulated_roi_band: "low" | "medium" | "high"; reason_codes: string[]; summary: string; resource_envelope_id: string; opportunity_costs: string[]; fallback_used: boolean; }
export interface ActionDelta { field: string; before: string | number | null; after: string | number | null; display_summary: string; trigger_refs: string[]; }
export interface DecisionReason { decision: string; trigger_ref: string; affected_fields: string[]; summary: string; }
export interface RejectedAlternative { alternative: string; rejection_basis: string; evidence_refs: string[]; }
export interface ChangeCondition { field: string; operator: "gt" | "gte" | "lt" | "lte" | "eq"; threshold: string | number; action_if_met: string; evidence_refs: string[]; }
export interface OpportunityCost { chosen_action: string; forgone_or_delayed_action: string; resource_source: string; summary: string; }
export interface DecisionTrace { schema_version: "decision-trace-v4"; trace_type: "province" | "automaker"; trace_id: string; branch_id: string; agent_id: string; round: SimulationRound; primary_goal: string; primary_choice: string; constraints: string[]; observations: Array<{ source_type: string; source_id: string; observation_type: string; summary: string; data_quality: V32DataQuality; evidence_refs: string[] }>; initial_action_id: string | null; alternatives_considered: string[]; final_action_id: string; action_delta: ActionDelta[]; decision_reasons: DecisionReason[]; rejected_alternatives: RejectedAlternative[]; change_conditions: ChangeCondition[]; opportunity_costs: OpportunityCost[]; coordination_proposal_refs: string[]; received_proposal_refs: string[]; coordination_response_refs: string[]; coordination_match_refs: string[]; fallback_reason: string | null; fallback_scope: string | null; reasoning_summary: string; evidence_refs: string[]; data_quality: V32DataQuality; confidence: "low" | "medium" | "high"; confidence_basis: string; affected_agents: string[]; peer_signals?: string[]; enterprise_signals?: string[]; received_enterprise_offer_refs?: string[]; enterprise_offer_response_refs?: string[]; }
export interface AutomakerSimulationPersona { automaker_id: string; primary_price_band: "mass_market" | "mainstream" | "premium"; technology_focus: string; growth_goal: number; cashflow_constraint: number; capacity_pressure: number; channel_expansion_tendency: number; rd_investment_tendency: number; intelligent_driving_stage: number; new_capacity_willingness: number; subsidy_sensitivity: number; market_sensitivity: number; supply_chain_sensitivity: number; regulation_sensitivity: number; data_quality: "proxy"; summary: string; }
export interface Relation { source_code: string; target_code: string; relation_type: "observation" | "competition" | "coordination"; weight: number; data_quality: V32DataQuality; evidence_refs: string[]; }
export interface M29ProfileSummary { schema_version: "province-profile-v6" | "automaker-profile-v2"; fact_summary: string[]; fact_refs: string[]; feature_values: Record<string, number>; feature_refs: Record<string, string>; data_quality: "proxy"; }
export interface M29BaselineMetadata { data_version: string; snapshot_hash: string; province_count: 31; automaker_count: 10; counts: Record<string, number>; quality_counts: Record<string, number>; acceptance_counts: Record<string, number>; missing_value_policy: string; relation_network_version: string; }
export interface ProvinceResourceEnvelope { envelope_id: string; available_policy_budget: number; consumer_cap: number; fixed_cost_cap: number; variable_cost_cap: number; fiscal_risk_limit: number; max_coordination_proposals: 2; max_active_matches: 1; max_enterprise_offers: 2; evidence_refs: string[]; }
export interface AutomakerResourceEnvelope { schema_version: "automaker-resource-envelope-v2"; envelope_id: string; national_market_budget: number; max_expand_provinces: number; facility_budget: number; max_facility_targets: number; cashflow_constraint: number; capacity_pressure: number; management_capacity: number; evidence_refs: string[]; }
export interface CompetitionOutcome { schema_version: "competition-outcome-v1"; outcome_id: string; branch_id: string; automaker_id: string; resource_type: "channel_slot" | "facility_slot"; winner_province_code: string; loser_province_code: string; winner_rank: number; loser_rank: number; relation_weight: number; loss_index: number; trigger_condition: string; evidence_refs: string[]; }
export interface TopKReallocation { schema_version: "top-k-reallocation-v1"; reallocation_id: string; branch_id: string; automaker_id: string; resource_type: "channel_slot" | "facility_slot"; released_province_code: string; recipient_province_code: string; reason: string; evidence_refs: string[]; }
export interface ProvinceUtility { schema_version: "province-utility-v1"; utility_id: string; branch_id: string; province_code: string; demand_index: number; industry_index: number; enterprise_gain: number; coordination_gain: number; fiscal_pressure: number; competition_loss: number; weights: Record<"demand" | "industry" | "enterprise" | "coordination" | "fiscal" | "competition", number>; utility_index: number; evidence_refs: string[]; }
export interface AutomakerCounterOffer { schema_version: "automaker-counter-offer-v1"; counter_offer_id: string; branch_id: string; offer_id: string; automaker_id: string; province_code: string; required_channel_share: number; required_industry_share: number; required_policy_focus: "consumer" | "fixed_cost" | "variable_cost" | "balanced"; validity_condition: string; opportunity_cost: string; evidence_refs: string[]; }
export interface ProvinceCounterOfferResponse { schema_version: "province-counter-offer-response-v1"; response_id: string; branch_id: string; counter_offer_id: string; province_code: string; decision: "accept" | "reject"; rejection_reason: string | null; opportunity_cost: string; change_condition: string; evidence_refs: string[]; }
export interface CoordinationProposal { proposal_id: string; branch_id: string; source_province_code: string; target_province_code: string; priority: 1 | 2; basis_type: "existing_relation" | "inferred_from_context"; cooperation_focus: "supply_chain" | "research_testing" | "operating_network"; offered_capability: string; requested_capability: string; source_success_delta: SubsidyMix; target_success_delta: SubsidyMix; fallback_delta: SubsidyMix; evidence_completeness: number; complementarity: number; goal_alignment: number; public_reason: string; evidence_refs: string[]; }
export interface CoordinationResponse { response_id: string; proposal_id: string; responding_province_code: string; decision: "accept" | "reject"; conditions_checked: string[]; rejection_reason: string | null; opportunity_cost: string; final_action_ref: string; evidence_refs: string[]; }
export interface CoordinationRecordV2 { coordination_id: string; proposal_id: string; response_id: string | null; left_province_code: string; right_province_code: string; status: "matched" | "unmatched" | "rejected" | "resource_invalid"; contribution: number; applied_action_refs: string[]; evidence_refs: string[]; summary: string; }
export interface ProvinceEnterpriseOffer { offer_id: string; branch_id: string; source_province_code: string; target_automaker_id: string; priority: 1 | 2; channel_commitment_share: number; industry_coordination_share: number; offered_support_scope: "consumer" | "fixed_cost" | "variable_cost" | "balanced"; activation_condition: string; opportunity_cost: string; public_reason: string; evidence_refs: string[]; }
export type EnterpriseCooperationAction = "channel_expansion" | "channel_maintenance" | "facility_new_plant" | "facility_expansion" | "facility_delay" | "industry_coordination" | "policy_support";
export interface ProvinceEnterpriseMatch { schema_version?: "province-enterprise-match-v1" | "province-enterprise-match-v2"; match_id: string; branch_id: string; offer_id: string; response_id: string | null; province_code: string; automaker_id: string; status: "matched" | "rejected" | "resource_invalid"; channel_contribution: number; industry_contribution: number; cooperation_actions?: EnterpriseCooperationAction[]; action_summary?: string; province_action_ref?: string | null; automaker_action_ref?: string | null; evidence_refs: string[]; summary: string; }
export interface AgentInvocation { invocation_id: string; agent_id: string; kind: string; model: string; run_mode: "fake" | "cache" | "live" | "fallback"; input_hash: string; output_hash: string; output_schema: string; fallback_used: boolean; }
export interface BranchRuntime { branch_id: string; kind: "control" | "treatment"; label: string; parent_checkpoint_id: string; policy: PolicyV4; event_applied: boolean; current_round: SimulationRound | null; completed_rounds: SimulationRound[]; province_resource_envelopes: Record<string, ProvinceResourceEnvelope>; automaker_resource_envelopes: Record<string, AutomakerResourceEnvelope>; province_initial_actions: Record<string, ProvinceActionV5>; province_proposed_actions: Record<string, ProvinceActionV5>; province_final_actions: Record<string, ProvinceActionV5>; automaker_initial_actions: Record<string, AutomakerActionV2>; automaker_negotiation_actions: Record<string, AutomakerActionV2>; automaker_final_actions: Record<string, AutomakerActionV2>; province_states: Record<string, ProvinceState>; national_metrics: NationalMetrics; decision_traces: DecisionTrace[]; province_coordination_proposals: CoordinationProposal[]; province_coordination_responses: CoordinationResponse[]; coordination_records: CoordinationRecordV2[]; province_enterprise_offers: ProvinceEnterpriseOffer[]; province_enterprise_offer_responses: ProvinceEnterpriseOfferResponse[]; province_enterprise_matches: ProvinceEnterpriseMatch[]; competition_outcomes: CompetitionOutcome[]; top_k_reallocations?: TopKReallocation[]; province_utilities: Record<string, ProvinceUtility>; automaker_counter_offers: AutomakerCounterOffer[]; province_counter_offer_responses: ProvinceCounterOfferResponse[]; consumer_responses: unknown[]; mechanism_totals: Record<string, number>; agent_invocations: AgentInvocation[]; }
export interface WorldStateV6 { schema_version: "world-state-v9" | "world-state-v8"; product_version?: "v3_2_m32"; experiment_id: string; journey_step: JourneyStep; status: string; interpretation: PolicyInterpretation; design: ExperimentDesign | null; baseline: BaselineSnapshot | null; branches: Record<string, BranchRuntime>; relation_network: { schema_version: string; relations: Relation[] } | null; automaker_personas: Record<string, AutomakerSimulationPersona>; seed: number; versions: Record<string, string>; }
export interface ComparisonV6 { schema_version: "comparison-v9"; experiment_id: string; experiment_type: ExperimentType; control_branch_id: string; treatment_branch_id: string; conclusion: string; gap_direction: "narrowed" | "widened" | "unchanged"; delta_gap: number; national_metrics: Record<string, { control: number; treatment: number; delta: number }>; province_deltas: Array<{ province_code: string; province_name: string; development_delta: number; demand_delta: number; industry_delta: number; fiscal_pressure_delta: number }>; automaker_deltas: Array<{ automaker_id: string; display_name: string; changed_province_count: number; maximum_intensity_delta: number; facility_changed: boolean }>; top_beneficiaries: string[]; top_pressured: string[]; fiscal_tradeoff: string; event_robustness: string; mechanism_chains: Array<{ category: "positive" | "cost" | "reversal_risk"; title: string; nodes: Array<{ node_type: "policy" | "agent_action" | "coordination_match" | "environment" | "metric"; ref: string; label: string; contribution: number | null }>; contribution_delta: number; evidence_refs: string[] }>; sensitivity_findings: Array<{ input_group: string; direction: string; affected_metric: string; local_effect: number; method_note: string }>; active_difference: "policy" | "event"; same_policy: boolean; same_event: boolean; checkpoint_id: string; competition_loss_delta: number; coordination_gain_delta: number; top_k_reallocation_count: number; counteroffer_acceptance_rate: number; }
export interface V32Event { schema_version: "event-v9"; event_id: string; type: string; experiment_id: string; branch_id: string | null; journey_step: JourneyStep; round: SimulationRound | null; timestamp: string; payload: Record<string, string | number | boolean | null>; }
export interface StrategyMarket { schema_version: "strategy-market-v3"; experiment_id: string; branches: Record<string, BranchRuntime>; automaker_signal_count: number; proposal_count: number; response_count: number; matched_count: number; enterprise_offer_count: number; enterprise_response_count: number; enterprise_matched_count: number; competition_outcome_count: number; counteroffer_count: number; counteroffer_response_count: number; top_k_reallocation_count: number; }
export interface PresentationSummary { schema_version: "presentation-summary-v1"; experiment_id: string; scenes: Array<{ scene: "policy_input" | "enterprise_feedback" | "province_coordination" | "resource_reallocation" | "policy_conclusion"; title: string; summary: string; evidence_refs: string[] }>; }
export interface ProvinceDetailV32 { experiment_id: string; province_code: string; profile: ProvinceProfile; m29_profile: M29ProfileSummary; persona: { summary: string; axes: Record<string, number>; key_constraints: string[] }; data_quality: "proxy"; data_quality_label: string; relations: Record<"observation" | "competition" | "coordination", Relation[]>; branches: Record<string, { resource_envelope: ProvinceResourceEnvelope | null; initial_action: ProvinceActionV5 | null; final_action: ProvinceActionV5 | null; state: ProvinceState | null; decision_traces: DecisionTrace[]; coordination_records: BranchRuntime["coordination_records"]; coordination_proposals: CoordinationProposal[]; coordination_responses: CoordinationResponse[]; enterprise_offers: ProvinceEnterpriseOffer[]; enterprise_matches: ProvinceEnterpriseMatch[]; enterprise_offer_responses: ProvinceEnterpriseOfferResponse[]; competition_outcomes: CompetitionOutcome[]; utility: ProvinceUtility | null; counter_offers: AutomakerCounterOffer[]; counter_offer_responses: ProvinceCounterOfferResponse[] }>; }
export interface AutomakerDetailV32 { experiment_id: string; automaker_id: string; profile: AutomakerProfile; m29_profile: M29ProfileSummary; simulation_persona: AutomakerSimulationPersona; data_quality: "proxy"; data_quality_label: string; branches: Record<string, { resource_envelope: AutomakerResourceEnvelope | null; initial_action: AutomakerActionV2 | null; negotiation_action: AutomakerActionV2 | null; final_action: AutomakerActionV2 | null; decision_traces: DecisionTrace[]; enterprise_offers: ProvinceEnterpriseOffer[]; enterprise_matches: ProvinceEnterpriseMatch[]; competition_outcomes: CompetitionOutcome[]; counter_offers: AutomakerCounterOffer[]; counter_offer_responses: ProvinceCounterOfferResponse[] }>; disclaimer: string; }
