import { useQuery } from "@tanstack/react-query";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";

import { policyScopeApi } from "../api/client";
import { Icon } from "../components/Icon";
import { usePolicyScopeContext } from "../context/PolicyScopeContext";

const axisLabels: Record<string, string> = { fiscal_capacity: "财政空间", industry_attraction: "产业吸引", consumption_activation: "消费激活", operating_cost_competitiveness: "运营成本竞争力", supply_chain_coordination: "供应链协同", peer_response_sensitivity: "同类省份响应" };
const mixLabels: Record<string, string> = { consumer: "消费端补贴", fixed_cost: "固定成本补贴", variable_cost: "可变成本补贴" };

export default function ProvinceAgentPage() {
  const flow = usePolicyScopeContext(); const navigate = useNavigate(); const { id, provinceCode } = useParams(); const [params, setParams] = useSearchParams(); const branch = params.get("branch") === "treatment" ? "treatment" : "control";
  const query = useQuery({ queryKey: ["province-detail-v2", id, provinceCode, flow.world?.phase], queryFn: () => policyScopeApi.getProvinceDetail(id!, provinceCode!), enabled: Boolean(id && provinceCode && flow.world) });
  if (query.isLoading) return <div className="v3-empty-page">正在加载省级 Agent…</div>;
  if (!query.data) return <div className="v3-empty-page"><h2>省级详情不可用</h2></div>;
  const detail = query.data; const snapshot = detail.branches[branch]; const action = snapshot?.current_action;
  const chooseBranch = (value: string) => { const next = new URLSearchParams(params); next.set("branch", value); setParams(next); };
  const eventMode = flow.world?.comparison_mode === "event_counterfactual";
  return <div className="v3-page"><button className="v3-back" onClick={() => navigate(`/experiments/${id}/live`)} type="button"><Icon name="arrow_back" />返回全国地图</button><div className="v3-province-hero"><div><span className="v3-kicker">省级 Agent · {detail.persona.primary_type}</span><h1>{detail.profile.name}</h1><p>{detail.persona.summary}</p></div><div className="v3-branch-switch"><button className={branch === "control" ? "active" : ""} onClick={() => chooseBranch("control")} type="button">{eventMode ? "无事件基线" : "原始方案"}</button><button className={branch === "treatment" ? "active" : ""} disabled={!detail.branches.treatment} onClick={() => chooseBranch("treatment")} type="button">{eventMode ? "事件情景" : "干预方案"}</button></div></div>
    {!snapshot ? <div className="v3-empty-page"><h2>该分支尚未创建</h2></div> : <><div className="v3-three-col">
      <section className="v3-card"><div className="v3-card-title"><Icon name="account_balance" /><div><small>财政空间</small><h2>本次实验省级决策画像</h2></div></div><div className="v3-bars">{Object.entries(detail.persona.axes).map(([key, value]) => <div key={key}><span>{axisLabels[key] ?? key}</span><i><b style={{ width: `${value * 100}%` }} /></i><strong>{(value * 100).toFixed(0)}</strong></div>)}</div></section>
      <section className="v3-card"><div className="v3-card-title"><Icon name="payments" /><div><small>三类补贴</small><h2>地方政策工具</h2></div></div>{action ? <><div className="v3-big-number"><strong>{(action.overall_support_intensity * 100).toFixed(1)}</strong><span>总体支持强度 / 100</span></div><div className="v3-bars">{Object.entries(action.subsidy_mix).map(([key, value]) => <div key={key}><span>{mixLabels[key]}</span><i><b style={{ width: `${value * 100}%` }} /></i><strong>{(value * 100).toFixed(0)}%</strong></div>)}</div><p>{action.summary}</p></> : <div className="v3-empty">等待 Q1 决策</div>}</section>
      <section className="v3-card"><div className="v3-card-title"><Icon name="hub" /><div><small>Peer 响应</small><h2>相似省份观察</h2></div></div><div className="v3-peer-list">{detail.top_k_neighbors.map((item) => <button key={item.province_code} onClick={() => navigate(`/experiments/${id}/provinces/${item.province_code}?branch=${branch}`)} type="button"><span>{item.province_name}</span><strong>{(item.weight * 100).toFixed(0)}</strong></button>)}</div><p>模式：{action?.peer_response_mode ?? "等待决策"}</p></section>
    </div><div className="v3-two-col">
      <section className="v3-card"><div className="v3-card-title"><Icon name="directions_car" /><div><small>车企反馈</small><h2>10 家全国性 Agent 在本省的投入</h2></div></div><div className="v3-company-response">{snapshot.automakers.map(({ profile, action: companyAction }) => { const market = companyAction?.province_market_actions.find((item) => item.province_code === provinceCode); return <button key={profile.automaker_id} onClick={() => navigate(`${location.pathname}?branch=${branch}&company=${profile.automaker_id}`)} type="button"><strong>{profile.display_name}</strong><span>{market ? `${market.channel_strategy} · ${(market.sales_investment_intensity * 100).toFixed(0)}` : "等待响应"}</span></button>; })}</div></section>
      <section className="v3-card"><div className="v3-card-title"><Icon name="functions" /><div><small>机制结果</small><h2>年度状态与临界点</h2></div></div><div className="v3-evidence-metrics"><div><span>需求指数</span><strong>{snapshot.state.demand_index.toFixed(1)}</strong></div><div><span>产业活动</span><strong>{snapshot.state.industry_activity_index.toFixed(1)}</strong></div><div><span>发展指数</span><strong>{snapshot.state.development_index.toFixed(1)}</strong></div><div><span>财政压力</span><strong>{snapshot.state.fiscal_pressure_index.toFixed(1)}</strong></div></div>{snapshot.feedback && <div className="v3-agent-note"><strong>年末复盘 · {snapshot.feedback.strategy_assessment}</strong><p>{snapshot.feedback.summary}</p></div>}</section>
    </div>{snapshot.event_signal && <section className="v3-card v31-province-event"><div className="v3-card-title"><Icon name="hub" /><div><small>Y2_Q3 · 两轮交互</small><h2>事件暴露与省际响应</h2></div></div><div className="v31-event-chain"><div><small>事件暴露</small><strong>{((snapshot.event_exposure ?? 0) * 100).toFixed(1)}</strong><span>{snapshot.event_signal.perception}</span></div><div><small>首轮信号</small><strong>{snapshot.event_signal.policy_focus}</strong><span>{snapshot.event_signal.summary}</span></div><div><small>Peer 响应</small><strong>{snapshot.event_response?.response_mode ?? "等待"}</strong><span>{snapshot.event_response?.observed_peer_codes.join("、") || "无"}</span></div><div><small>协作状态</small><strong>{snapshot.coordination_matches.some((item) => item.status === "matched") ? "已匹配" : snapshot.coordination_matches.length ? "单向未匹配" : "未提议"}</strong><span>{snapshot.coordination_matches.map((item) => `${item.left_province_code}↔${item.right_province_code}`).join("、") || "—"}</span></div></div><div className="v3-chip-row">{Object.entries(snapshot.mechanism_summary).map(([key, value]) => <span key={key}>{key} {value.toFixed(2)}</span>)}</div></section>}</>}
  </div>;
}
